[build]
cmd = "ls && go build -o ./tmp/main.exe ."
#bin = "./build/main.exe"
#full_bin = "cmd /C \"set APP_ENV=dev && set APP_USER=air && ./build/main.exe\""
#include_ext = ["go", "tpl", "tmpl", "html"]
#exclude_dir = ["assets", "tmp", "vendor"]
#exclude_file = ["*_test.go"]
#exclude_regex = ["^/tmp/"]
#delay = 1000 # ms
#stop_on_error = true
#kill_signal = "kill"
#kill_timeout = 1000 # ms

[log]
level = "debug"
color = true
timestamp = false

[serve]
#watch_dir = ["."]
#watch_ext = ["go", "tpl", "tmpl", "html"]
#ignore_dir = ["assets", "tmp", "vendor"]
#ignore_file = ["*_test.go"]
#ignore_regex = ["^/tmp/"]
#bin = "./build/main.exe"
#cmd = "ls && cmd /C \"set APP_ENV=dev && set APP_USER=air && ./build/main.exe\""
delay = 1000 # ms
grace = 1000 # ms
kill_signal = "kill"
kill_timeout = 1000 # ms